---
-
  hosts: webserver
  tasks:
   
    - name: add motd content using content line
      copy:
        content: welcome to webserver servers - Ansible Rocks
        dest: /etc/motd
   
    - name: configure name
      ios_config:
        lines: hostname{{ hostname.name }}
...
