---
-
  hosts: webserver
  gather_facts: False
  Vars:
    named_lists:
      - item1
      - item2
      - item3
      - item4
  tasks:
    - name: Test named list
      debug: 
        msg: "{{ named_lists }}"
    - name: Test named list item method1
      debug:
        msg: "{{ named_lists.0 }}"
    - name: Test name list itemm method2
      debug:
        msg: "{{ named_list[0] }}"
...
